### PR TITLE
added cert script

### PR DESCRIPTION
**Pull request by kikiya**
script to enable students to download their server certs as long as they are authenticated with ccloud

### CODE REVIEW

**Comment by rthurimella** [comment]
I am unaware of how this script gets executed in the end by the learners? I am guessing they won't be running the script as root.

I checked the instructions and they look good. I ran the script to cover common mistakes the learners are likely to make:

1. Running the script without a cluster name,
2. Running the script with a wrong cluster name, and
3. Running the script multiple times 

The error handling is sufficient.

**Review by rthurimella — APPROVED** [review]
I checked the instructions and they look good. I ran the script to cover common mistakes the learners are likely to make:

1. Running the script without a cluster name,
2. Running the script with a wrong cluster name, and
3. Running the script multiple times

The error handling is sufficient.

The only context I am missing is how this script gets executed in the end by the learners. I am guessing they won't be running it as root.

**Comment by kikiya** [comment]
Thank you!

Students will run the script from the VM. 

Could you take a look over the updated exercise instructions and let me know if things work as expected in Instruqt?

**Comment by rthurimella** [comment]
I understand they will be running it from the VM that is part of Instruqt, but as which user? 

Because when I login, I get logged  in as root and script rejects to run with an error message "Don't run this command as root."

**Pull request merged**
